name: github pages

on:
  push:
    branches:
      - master
    tags: 
        - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - run: yarn docs
      - run: |
          PACKAGE_VERSION=$(cat package.json|jq -r '.version')
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
          echo "DESTINATION=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/node-openjtalk-binding/${{ env.PACKAGE_VERSION }}
          destination_dir: ${{ env.DESTINATION }}