name: npm-publish

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          PACKAGE_VERSION=$(cat package.json|jq -r '.version')
          HOMEPAGE=$(cat package.json|jq -r '.homepage')
          [[ "v${PACKAGE_VERSION}" == ${HOMEPAGE##*/} ]]
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}