name: Prebuild
on:
  release:
    types: [published]

jobs:
  build:
    name: Prebuild
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-22.04, ubuntu-20.04, ubuntu-18.04, windows-2019]
        node: [16, 18]
        exclude:
          - os: ubuntu-18.04
            node: [18]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install
        env:
          npm_config_build_from_source: true

      - name: Package prebuild
        run: yarn run build

      - name: prebuild package
        run: yarn add -D node-gyp
        
      - name: Upload prebuild asset
        uses: icrawl/action-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: "build/stage/**/*.tar.gz"

  build_musl:
    name: Prebuild (musl)
    runs-on: ubuntu-latest
    container:
      image: node:${{ matrix.node }}-alpine
    strategy:
      matrix:
        node: [16, 18]
    steps:
      - name: Setup env with Node v${{ matrix.node }}
        run: |
          apk add --update
          apk add --no-cache ca-certificates git curl build-base python3 g++ make
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install
        env:
          npm_config_build_from_source: true
  
      - name: Package prebuild
        run: yarn build

      - name: prebuild package
        run: yarn add -D node-gyp

      - name: Upload prebuild asset
        uses: icrawl/action-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: "build/stage/**/*.tar.gz"

  publish-prerelease:
    runs-on: ubuntu-latest
    needs: [build, build_musl]
    if: github.event.release.prerelease
    steps:
      - uses: actions/checkout@v2
      - run: |
          PACKAGE_VERSION=$(cat package.json|jq -r '.version')
          HOMEPAGE=$(cat package.json|jq -r '.homepage')
          [[ "v${PACKAGE_VERSION}" == ${HOMEPAGE##*/} ]]
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: next

  publish-release:
    runs-on: ubuntu-latest
    needs: [build, build_musl]
    if: ${{ !github.event.release.prerelease }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          PACKAGE_VERSION=$(cat package.json|jq -r '.version')
          HOMEPAGE=$(cat package.json|jq -r '.homepage')
          [[ "v${PACKAGE_VERSION}" == ${HOMEPAGE##*/} ]]
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
